export default defineEventHandler(async () => {
    return [
        "Dominik",
        "Hussain",
        "Halil",
        "Simon",
        "Daniel",
        "Massih",
        "Lea",
        "Manuel",
        "Mikail",
        "Asia,
        "Elina",
        "Carolina",
        "Lana",
        "Luca",
        "Lorena",
        "Linus",
        "Enrico",
        "Felix",
        "Laurin",
        "Emina",
        "Naz Fatma",
        "Jannik",
        "Christian",
        "Elias",
        "Jeremy",
        "Mia",
        "Noah"
    ]
})
